/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'primary':                  '#2563eb',
        'primary-container':        '#1d4ed8',
        'on-primary':               '#ffffff',
        'on-primary-container':     '#dbeafe',
        'secondary':                '#64748b',
        'secondary-container':      '#f1f5f9',
        'on-secondary-container':   '#475569',
        'tertiary':                 '#16a34a',
        'tertiary-container':       '#bbf7d0',
        'on-tertiary-container':    '#14532d',
        'surface':                  '#f8fafc',
        'surface-bright':           '#ffffff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low':    '#f8fafc',
        'surface-container':        '#f1f5f9',
        'surface-container-high':   '#e2e8f0',
        'surface-container-highest':'#cbd5e1',
        'on-surface':               '#0f172a',
        'on-surface-variant':       '#6b7280',
        'outline':                  '#e5e7eb',
        'outline-variant':          '#f3f4f6',
        'inverse-surface':          '#1e293b',
        'inverse-on-surface':       '#f8fafc',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body:     ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm:      '0.125rem',
        md:      '0.375rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        '2xl':   '1rem',
        '3xl':   '1.5rem',
        full:    '9999px',
      },
      boxShadow: {
        ambient: '0px 12px 32px rgba(24,28,30,0.06)',
        float:   '0px 20px 48px rgba(24,28,30,0.10)',
      },
      animation: {
        'fade-up':    'fadeUp 0.5s ease forwards',
        'pulse-slow': 'pulseSlow 2s cubic-bezier(.4,0,.6,1) infinite',
        'bar-grow':   'barGrow 0.6s cubic-bezier(.22,1,.36,1) both',
        'popup-in':   'popupIn .35s cubic-bezier(.22,1,.36,1) forwards',
      },
      keyframes: {
        fadeUp:    { from:{opacity:0,transform:'translateY(20px)'}, to:{opacity:1,transform:'translateY(0)'} },
        pulseSlow: { '0%,100%':{opacity:1,transform:'scale(1)'}, '50%':{opacity:.6,transform:'scale(1.3)'} },
        barGrow:   { from:{transform:'scaleY(0)'}, to:{transform:'scaleY(1)'} },
        popupIn:   { from:{opacity:0,transform:'translateY(12px) scale(.97)'}, to:{opacity:1,transform:'translateY(0) scale(1)'} },
      },
    },
  },
  plugins: [],
}
