"""add search cache

Revision ID: 5fba3585c182
Revises: 2354cd91667f
Create Date: 2026-05-03 12:50:16.721889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5fba3585c182'
down_revision: Union[str, None] = '2354cd91667f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(length=500), nullable=False),
    sa.Column('stores', sa.JSON(), nullable=False),
    sa.Column('best_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_cache_query'), 'search_cache', ['query'], unique=True)
    op.create_index(op.f('ix_search_cache_timestamp'), 'search_cache', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_cache_timestamp'), table_name='search_cache')
    op.drop_index(op.f('ix_search_cache_query'), table_name='search_cache')
    op.drop_table('search_cache')
    # ### end Alembic commands ###
