"""add_is_superuser

Revision ID: 8058a8219ce4
Revises: 
Create Date: 2026-04-17 10:01:09.848955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8058a8219ce4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scraper_sessions_domain', table_name='scraper_sessions')
    op.drop_index('ix_scraper_sessions_status', table_name='scraper_sessions')
    op.drop_table('scraper_sessions')
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_superuser')
    op.create_table('scraper_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('domain', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('bot_email', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('bot_phone', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('cookies_enc', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('logged_in_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_checked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('successful_uses', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('failed_uses', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('login_attempts', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='scraper_sessions_pkey')
    )
    op.create_index('ix_scraper_sessions_status', 'scraper_sessions', ['status'], unique=False)
    op.create_index('ix_scraper_sessions_domain', 'scraper_sessions', ['domain'], unique=True)
    # ### end Alembic commands ###
